{
  getObjects(
    bucket_slug: "craig"
    input: {
      read_key: "iHIswEFFeDTFbP1XKoLC3gEV2fCSXgtXPXzC9OQNStzwqX0FdM"
      type: "blogs"
    }
  ) {
    objects {
      _id
      slug
      title
      content
      metadata
      published_at
      order
    }
    total
  }
}
